---
pull_request_rules:
  - name: Auto-merge dependabot updates when checks pass
    conditions:
      - author=dependabot[bot]
      - label!=wontfix
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: merge
  - name: Auto-merge when all checks pass and the PR has been approved
    conditions:
      - "#review-requested=0"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Ask for reviews
    conditions:
      - -closed
      - -draft
      - -author=dependabot[bot]
    actions:
      request_reviews:
        teams:
          - devs
  - name: Assign PR to its author
    conditions:
      - "#files=1"
    actions:
      assign:
        add_users:
          - "{{author}}"
