# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  # Disable standard style linters in favour of eslint
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD
  # Not needed in this repository
  - REPOSITORY_TRIVY
  # Disable scss-lint in favour of stylelint
  - CSS_SCSS_LINT

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

# Config paths
CSS_STYLELINT_CONFIG_FILE: stylelint.config.js
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
