pull_request_rules:
  - name: Auto request reviews
    conditions:
      - author~=!^dependabot(|-preview)\[bot\]$
    actions:
      request_reviews:
        users:
          - DanWebb
          - gavmck
        random_count: 1
  - name: Autosquash when checks pass and reviews are approved
    conditions:
      - and:
        - author~=!^dependabot(|-preview)\[bot\]$
        - label!=wontfix
        - check-success=build
        - check-success=SonarCloud Code Analysis 
        - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
  - name: Autosquash security updates when checks pass
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label!=wontfix
      - check-success=build
      - check-success=SonarCloud Code Analysis 
    actions:
      merge:
        method: squash
